ARG IMAGE=node:18.20.5-alpine
ARG NODE_ENV=production

FROM $IMAGE as deps

RUN apk add --no-cache python3 py3-pip make g++

COPY --chown=node:node dist/apps/dsb-client-gateway-scheduler/package.json /usr/app/
COPY --chown=node:node package-lock.json /usr/app/
COPY --chown=node:node package.json /usr/app/root-package.json
COPY --chown=node:node ci/Docker/apply-overrides.js /usr/app/

WORKDIR /usr/app
RUN node apply-overrides.js package.json root-package.json && npm ci --omit=dev


FROM $IMAGE

ENV NODE_ENV=$NODE_ENV

COPY --chown=node:node dist/apps/dsb-client-gateway-scheduler/* /usr/app/
COPY --from=deps --chown=node:node /usr/app/node_modules /usr/app/node_modules

WORKDIR /usr/app

USER node

CMD ["node", "main.js"]
