ARG IMAGE=node:22.21.1-alpine

FROM $IMAGE

RUN apk add --no-cache python3 py3-pip make g++

RUN npm install -g pnpm@11

RUN chown -R node:node /usr/src/app

WORKDIR /usr/src/app

COPY --chown node:node . ./

RUN pnpm install --frozen-lockfile
