ARG IMAGE=node:16.10
ARG NODE_ENV=production

FROM $IMAGE as build
ENV CYPRESS_INSTALL_BINARY=0

WORKDIR /usr/usr/app

COPY . .

ENV NODE_ENV=$NODE_ENV

RUN npm install --quiet --no-progress -g nx npm@8.5.0 && \
    npm ci --quiet --no-progress

CMD ["nx", "serve", "dsb-client-gateway-frontend"]
