ARG IMAGE=node:22.21.1-alpine
ARG NODE_ENV=production

FROM $IMAGE as deps

RUN apk add --no-cache python3 py3-pip make g++

RUN npm install -g pnpm@11

COPY --chown=node:node dist/apps/dsb-client-gateway-scheduler/package.json /usr/app/
COPY --chown=node:node pnpm-lock.yaml /usr/app/

WORKDIR /usr/app
RUN echo "package-import-method=copy" > .npmrc
RUN pnpm install --prod --no-frozen-lockfile --dangerously-allow-all-builds && pnpm add tslib


FROM $IMAGE

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

COPY --chown=node:node dist/apps/dsb-client-gateway-scheduler/* /usr/app/
COPY --from=deps --chown=node:node /usr/app/node_modules /usr/app/node_modules

WORKDIR /usr/app

USER node

CMD ["node", "main.js"]
