ARG IMAGE=node:16.10-alpine

FROM $IMAGE

RUN chown -R node:node /usr/src/app

WORKDIR /usr/src/app

COPY --chown node:node . ./

RUN apk add --no-cache python3 py3-pip make g++ && \
    npm ci

#COPY --chown=node:node dist/apps/dsb-client-gateway-api/* /usr/app/
#COPY --chown=node:node package-lock.json /usr/app/
#
#WORKDIR /usr/app
#RUN npm ci --production
#
#USER node
