openapi: 3.0.1
info:
  title: DSB Client Gateway
  description: The DSB Client Gateway acts as a client to the Energy Web Decentralized Service Bus (DSB), allowing it to publish and subscribe to  messages on particular channels.
  contact:
    email: dsb@energyweb.org
  version: 0.1.0
tags:
  - name: Config
    description: Manage the DSB Client Gateway as admin
  - name: Message
    description: Send and retrieve messages on the DSB
  - name: Channels
    description: Find information on available channels
  - name: Docs
    description: Download API schemas
paths:
  /api/v1/config/identity:
    post:
      tags:
        - Config
      summary: Sets the decentralized identity of the gateway, enroling it on to DSB
      operationId: createIdentity
      requestBody:
        description: The private key which will be associated with the DID
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdentityConfig'
      responses:
        '200':
          description: The private key was accepted and saved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'
        default:
          description: Error processing request
          content:
            application/json:
              example:
                err: ID::INVALID_PRIVATE_KEY
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - basicAuth: []
    get:
      tags:
        - Config
      summary: Gets the public information of the configured identity
      operationId: getIdentity
      responses:
        '200':
          description: The public key and balance of the configured private key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'
  /api/v1/config/enrol:
    post:
      tags:
        - Config
      summary: Requests enrolment with the configured identity.
      description: On success, starts a listener for claim approval. On approval of desired claim(s), syncs them to the subject's DID Document. Note that this event can be missed, in which case the subject must manually sync them via Switchboard. Note this endpoint can be called again to restart the claim approval listener in the event that the claim(s) have not yet been approved but the listener was removed, for instance during a restart of the application.
      operationId: createEnrolment
      responses:
        '200':
          description: A DID was created and enrolment requested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enrolment'
    get:
      tags:
        - Config
      summary: Gets the current enrolment state
      operationId: getEnrolment
      responses:
        '200':
          description: The created DID and current enrolment state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enrolment'
  /api/v1/message:
    post:
      tags:
        - Message
      summary: Send message on a DSB channel
      operationId: createMessage
      requestBody:
        description: Unsigned message to be published on desired channel
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessage'
      responses:
        '200':
          description: The message was successfully published
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMessageSuccess'
        default:
          description: Error processing request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - basicAuth: []
    get:
      tags:
        - Message
      summary: Consume messages from a DSB channel
      operationId: getMessage
      parameters:
        - in: query
          name: fqcn
          required: true
          description: Fully Qualified Channel Name
          example: test.channels.dsb.apps.energyweb.iam.ewc
          schema:
            type: string
        - in: query
          name: amount
          required: false
          default: 1
          description: Amount of messages that should be retrieved
          schema:
            type: number
      responses:
        '200':
          description: The array of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        default:
          description: Error processing request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - basicAuth: []
  /api/v1/channels:
    get:
      tags:
        - Channels
      summary: Retreive channels with publisher or subcriber rights
      operationId: getChannels
      responses:
        '200':
          description: The array of channels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Channel'
        default:
          description: An error occurred retrieving the channels
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - basicAuth: []
  /api/v1/docs/rest.yaml:
    get:
      tags:
        - Docs
      summary: Retrieve this Open API schema in YAML
      operationId: getOpenAPISchema
      responses:
        '200':
          description: The YAML schema file
  /api/v1/docs/ws.yaml:
    get:
      tags:
        - Docs
      summary: Retrieve the Async API schema in YAML
      operationId: getAsyncAPISchema
      responses:
        '200':
          description: The YAML schema file
components:
  schemas:
    IdentityConfig:
      type: object
      properties:
        privateKey:
          type: string
          description: Ethereum compliant hex-encoded private key
    Identity:
      type: object
      properties:
        address:
          type: string
        publicKey:
          type: string
        balance:
          type: string
          enum:
            - NONE
            - LOW
            - OK
    Enrolment:
      type: object
      properties:
        did:
          type: string
        state:
          type: object
          properties:
            ready:
              type: boolean
            waiting:
              type: boolean
            roles:
              type: object
              properties:
                user:
                  $ref: '#/components/schemas/RoleState'
                messagebroker:
                  $ref: '#/components/schemas/RoleState'
    SendMessage:
      type: object
      properties:
        fqcn:
          description: Fully Qualified Channel Name
          example: test.channels.dsb.apps.energyweb.iam.ewc
          type: string
        payload:
          description: Message data conforming to channel
          example: '{"some": "data"}'
          type: string
    SendMessageSuccess:
      type: object
      properties:
        id:
          description: Message ID on the DSB
          example: msg-#22
          type: string
    Message:
      type: object
      properties:
        id:
          description: Message ID
          type: string
        payload:
          description: The message data
          type: string
        signature:
          description: Ethereum (secp256k1) Signature corresponding to the payload as signed by the private key of the sender
          type: string
        sender:
          description: DID of the sender of the message
          type: string
    Channel:
      type: object
      properties:
        fqcn:
          description: Fully-qualified channel name
          example: test.channels.dsb.apps.energyweb.iam.ewc
          type: string
        topics:
          type: object
          properties:
            namespace:
              description: The name of the topic within the channel
              example: offers
              type: string
            schema:
              description: JSON Schema object or string (only JSON currently supported)
              example: "{\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"$id\":\"0d0db676-4da7-414e-a36c-a4b62b151d22\",\"title\":\"test\",\"type\":\"object\",\"required\":[\"id\",\"name\"],\"properties\":{\"id\":{\"type\":\"integer\"},\"name\":{\"type\":\"string\"}}}"
              type: string
        admins:
          description: Array of DIDs allowed to manage the channel
          example: ["did:ethr:0x3E8c2db768f876907C54F52B9e6Cc7F8E48d850F"]
          type: array
          items:
            type: string
        publishers:
          description: Array of DIDS and/or role authorized to pubish on the channel
          example: ["did:ethr:0x3E8c2db768f876907C54F52B9e6Cc7F8E48d850F", "user.roles.dsb.apps.energyweb.iam.ewc"]
          type: array
          items:
            type: string
        subscribers:
          description: Array of DIDS and/or role authorized to subscribe to the channel
          example: ["did:ethr:0x3E8c2db768f876907C54F52B9e6Cc7F8E48d850F", "user.roles.dsb.apps.energyweb.iam.ewc"]
          type: array
          items:
            type: string
        maxMsgAge:
          description: Duration a message lives until it is removed from persistent storage (nanoseconds)
          example: 86400000000
          type: number
        maxMsgSize:
          description: Size of messages allowed on the channel (bytes)
          example: 10240
          type: number
        createdBy:
          description: The DID that created the channel
          example: "did:ethr:0x3E8c2db768f876907C54F52B9e6Cc7F8E48d850F"
          type: string
        createdDateTime:
          description: Timestamp of when the channel was created (ISO 8601 UTC)
          example: "2021-08-19T11:40:43.303Z"
          type: string
        modifiedBy:
          description: The DID of the admin that last modified the channel
          example: "did:ethr:0x3E8c2db768f876907C54F52B9e6Cc7F8E48d850F"
          type: string
        modifiedByDateTime:
          description: Timestamp of when the channel was modified last (ISO 8601 UTC)
          example: "2021-08-20T11:40:43.303Z"
    Error:
      type: object
      properties:
        err:
          type: string
    RoleState:
      type: string
      enum:
        - NO_CLAIM
        - AWAITING_APPROVAL
        - APPROVED
        - NOT_WANTED
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
