export enum DsbClientGatewayErrors {
  // IDENTITY ERRORS
  ID_NO_PRIVATE_KEY = 'ID::NO_PRIVATE_KEY',
  ID_INVALID_PRIVATE_KEY = 'ID::INVALID_PRIVATE_KEY',
  ID_IAM_INIT_ERROR = 'ID::IAM_INIT_ERROR',
  ID_FETCH_CLAIMS_FAILED = 'ID::FETCH_CLAIMS_FAILED',
  ID_CREATE_CLAIM_FAILED = 'ID::CREATE_CLAIM_FAILED',
  ID_NO_DID = 'ID::NO_DID',
  ID_BALANCE_CHECK_FAILED = 'ID::BALANCE_CHECK_FAILED',
  ID_NO_BALANCE = 'ID::NO_BALANCE',
  ID_ALREADY_ENROLED = 'ID::ALREADY_ENROLED',
  ID_NOT_ENROLED = 'ID::NOT_ENROLED',

  // MESSAGE BROKER ERRORS
  MB_UNABLE_TO_LOGIN = 'MB::UNABLE_TO_LOGIN',

  // Channel errors

  CHANNEL_ALREADY_EXISTS = 'CHANNEL::ALREADY_EXISTS',
  CHANNEL_NOT_FOUND = 'CHANNEL::NOT_FOUND',
  CHANNEL_RESTRICTED_FIELDS_UPDATE = 'CHANNEL::RESTRICTED_FIELDS_UPDATE',
  CHANNEL_TYPE_INVALID = 'CHANNEL::TYPE_INVALID',

  // Topic errors

  TOPIC_NOT_FOUND = 'TOPIC::NOT_FOUND',
  TOPIC_NOT_RELATED_TO_CHANNEL = 'TOPIC::NOT_RELATED_TO_CHANNEL',

  // DSB ERRORS
  DSB_NOT_CONTROLLABLE = 'DSB::NOT_CONTROLLABLE',
  DSB_UNSUPPORTED_CONTROL_TYPE = 'DSB::UNSUPPORTED_CONTROL_TYPE',
  DSB_UNHEALTHY = 'DSB::UNHEALTHY',
  DSB_REQUEST_FAILED = 'DSB::REQUEST_FAILED',
  DSB_LOGIN_FAILED = 'DSB::LOGIN_FAILED',
  DSB_UNAUTHORIZED = 'DSB::UNAUTHORIZED',
  DSB_FORBIDDEN_RESOURCE = 'DSB::FORBIDDEN_RESOURCE',
  DSB_CHANNEL_UNAUTHORIZED = 'DSB::CHANNEL_UNAUTHORIZED',
  DSB_CHANNEL_NOT_FOUND = 'DSB::CHANNEL_NOT_FOUND',
  DSB_NO_SUBSCRIPTIONS = 'DSB::NO_SUBSCRIPTIONS',
  GW_INVALID_PAYLOAD = 'DSB::INVALID_PAYLOAD',

  // PM2 ERRORS
  PM2_NOT_CONFIGURED = 'PM2::NOT_CONFIGURED',
  PM2_CONNECT_FAILED = 'PM2::CONNECT_FAILED',
  PM2_DISCONNECT_FAILED = 'PM2::DISCONNECT_FAILED',
  PM2_START_FAILED = 'PM2::START_FAILED',
  PM2_RESTART_FAILED = 'PM2::RESTART_FAILED',

  // WEB3 ERRORS
  WEB3_PROVIDER_ERROR = 'WEB3::PROVIDER_ERROR',

  // GENERAL ERRORS
  DISK_READ_FAILED = 'DISK_READ_FAILED',
  DISK_WRITE_FAILED = 'DISK_WRITE_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  BAD_REQUEST = 'BAD_REQUEST',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_FILE = 'INVALID_FILE',

  // SIGNATURE ERRORS
  SIGNATURE_CHECK_FAILED = 'SIG::CHECK_FAILED',
  SIGNATURE_DOES_NOT_MATCH = 'SIG::NO_MATCH',

  // Messaging ERRORS
  RECIPIENTS_NOT_PRESENT = 'MESSAGING::RECIPIENTS_NOT_PRESENT',
  MESSAGES_NOT_PRESENT = 'MESSAGING::MESSAGES_NOT_PRESENT',
  TOPIC_OWNER_AND_NAME_REQUIRED = 'MESSAGING::TOPIC_OWNER_AND_NAME_REQUIRED',
  MESSAGE_DECRYPTION_FAILED = 'MESSAGING::DESCRPTION_FAILED',
  //File upload errors

  FILE_SIZE_GREATER_THEN_100_MB = 'MESSAGING::FILE_SIZE_GREATER_THEN_100_MB',
  FILE_TYPE_NOT_MATCHED = 'MESSAGING::FILE_TYPE_NOT_MATCHED',
  FILE_NOT_FOUND = 'MESSAGING::FILE_NOT_FOUND',
}

export const DsbMessageBrokerErrors = {
  10: 'UNAUTHORIZE ACCESS',
  12: 'OWNER: VALIDATION FAILED',
  13: 'SCHEMA VALIDATION FAILED',
  14: 'REQUIRED TO SET LIMIT WITH PAGE > 1',
  15: 'CANNOT PARSE JSON',
  16: 'RELATED JAVA: ILLEGALARGUMENTEXCEPTION VALIDATION',
  17: 'RELATED PARAMETER VALIDATION',
  20: 'RELATED TO NATS JETSTREAM EXCEPTION',
  21: 'FQCN NOT EXISTS',
  30: 'RELATED TO CAMEL EXCEPTION',
  40: 'RELATED TO AZURE STORAGE EXCEPTION',
  50: 'RELATED TO MONGODB EXCEPTION',
  51: 'RELATED DUPLICATION',
  60: 'RELATED TO GENERAL SERVER EXCEPTION',
};
