# Default values for ddhub-client-gateway-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ddhub-client-gateway-api:
  replicaCount: 2

  clientgateway:
    envVars :
      CACHE_SERVER_URL: https://identitycache-dev.energyweb.org/v1
      DSB_BASE_URL: http://ddhub-messagebroker-proxy-test.ddhub-test.svc
      RPC_URL: https://volta-rpc-vkn5r5zx4ke71f9hcu0c.energyweb.org/
      EVENT_SERVER_URL: https://identitycache-dev.energyweb.org
      PARENT_NAMESPACE: ddhub.apps.energyweb.iam.ewc
      SECRETS_ENGINE: azure
      VAULT_ENDPOINT: http://vault.ddhub-dev.svc:8200
      SECRET_PREFIX: "ddhubtest1/"
      NODE_ENV: test
      OPENTELEMETRY_ENABLED: false
      EVENTS_MAX_PER_SECOND: "200"
      NO_COLOR: "true"
      IPFS_HOST: "ipfs.infura.io"
      IPFS_PROTOCOL: "https://"
      IPFS_PORT: "5001"
      AZURE_VAULT_URL: https://aemo-vc-vault.vault.azure.net
      NEXT_PUBLIC_PARENT_NAMESPACE: ddhub.apps.energyweb.iam.ewc
      CHAIN_ID: 73799
      DID_AUTH_URL: http://ddhub-messagebroker-proxy-test.ddhub-test.svc
      PORT: 3333
      WEBSOCKET: NONE
      WEBSOCKET_RECONNECT: false
      EVENTS_EMIT_MODE: BULK
      MTLS_ENABLED: false
    ui:
      image:
        repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-frontend
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: 656eb648-bb0f-4e50-9684-297394e27acb
    scheduler:
      enabled: true
      image:
        repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-scheduler
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: 656eb648-bb0f-4e50-9684-297394e27acb
      extraEnvVars:
        DID_REGISTRY_ADDRESS: "0xc15d5a57a8eb0e1dcbe5d88b8f9a82017e5cc4af"
  image:
    # repository: 098061033856.dkr.ecr.us-east-1.amazonaws.com/ew-dos-dsb-ecr
    repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 656eb648-bb0f-4e50-9684-297394e27acb

  imagePullSecrets: []
  nameOverride: "ddhub-client-gateway-api-test-2"
  fullnameOverride: "ddhub-client-gateway-api-test-2"

  podSecurityContext:
    fsGroup: 2000

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      cert-manager.io/issuer: prod-issuer
      cert-manager.io/issuer-kind: OriginIssuer
      cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
    hosts:
      - host: ddhub-gateway-test-2.energyweb.org
        paths:
        - path: /docs
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-api-test-2
            servicePort: 80
        - path: /api
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-api-test-2
            servicePort: 80
        - path: /docs-json
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-api-test-2
            servicePort: 80
        - path: /events
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-api-test-2
            servicePort: 80
        - path: /
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-api-test-2-ui
            servicePort: 80
    tls:
      - secretName: ddhub-gateway-test-tls-secret
        hosts:
          - ddhub-gateway-test-2.energyweb.org

  probes:
    liveness: true
    livenessInitialDelay: 120
    livenessPeriodSeconds: 10
    readiness: true
    readinessInitialDelay: 120

  sealedSecret:
    enabled: true
    encryptedData:
      AZURE_CLIENT_ID: AgDVObsXY7peJMjC9FWskXZ7G1qDwJAqVPmHXWMZ0jebdjsUQNqV4OsWpf9evKbv4ImahaW29Hac3kMBfr9oKhpCTJGNgeCbZHCU/tKxgkNK44Y6RA/TrNLueZV64ZhT99bYnrKh7G69CGLqfRs0HkR/CQlA+6B2eFYyYYJTl/vvfyp3fPYL5bSW2QP+LiGmIMSskmdnEDhAPNdSa0tbT8N95iHE/Jv0imUwmKU+iF/BXHAXY7+WYT01CRwCjI8i3MTCfZl03sS/RiQPBgFAt+pcAdDFhWoZjJB0C0Y4/157kX1ziVBmxsWRsfk3K4LzxmwkpzcXeVxiMFosnSgciMBxNpeXlIye+vTn6Q4BrI8g17lxu79O93ycyEM+BZtKwbzlgmhytiXwKK1c9pZ/ndlTVdY1aarznujmGvKMGBJmXFuGKNZqJDLkdiNnAT37Kv16QSPLi5qgyDBmDEHZGftLJe8QHRF5MYURuZ8Fxo/ye/5DWjenu781P0d91FkqERGkncxnh2Ad7tAYrsbt1HEpMNd6x/FcL/MLbiC2xcTfKEbmtBHeJvHb2qkA6NQTqyqsHHS6f5vAfFPJJgWCo5SaUmO4GvYRqLNIVYY6zlLXf9QOxstWJrTrqhttToObE6nOZ/i6294nGtuyKkztC3PKTkLrxON7RtuJc9f4FkTOqajxsmnpf/BJz0IQzIgmztlib7hUWSN3lxp4hIHIcqPXZYZaCWeeUgYxH+fIMN+JNVY68rk=
      AZURE_CLIENT_SECRET: AgDMQhwrpntGBo9a4ArFmKe6SjWrIkGE+pISLCNQbuLFPXwtvNiEj6eXP2tem+uAnILByu7Hzc8wJf85m+nIkPZtrVxrTVQoeHbxUNgHscck/yHha7bVNBW9k6PnkDkZZJK4YVH//FufSGIBjEOJJlPXWLKkupZegc8okXJhDVqUJ8mkrRMlDROTHDuvoQcabfrsppK0Qswukyrt4B8lEmxTQDOQxKM1nhcS7deugMEPo5Kt3xmY6xKXVsqhul4UPmp5bBC217jWzmzVH+bJmyGlJO8HnV/pmDH2rnxUwPB10PjXBBR1QP/hIEwTV1zqG1tu159lmBLwvg32LCFhS2+hAWI019XSv6zPzZgNSTUnmK0cOEXbi8502kfUauwz2rBE0IolCERbt4LSia02qXA1VVNrCmxXgzjv+n3MszhX9RXZZ5x2uGA0cl1oLz3Cbt+bBED7VrDclq4Ylato5iQx9Ut5IcakqvqXL0rw+27s3AmhcllRbbBSeKltv0TZcsyTVFYLFtptvoc2mwuQBypmBDkEZ4PPd5O0GnmhtTs3yp9hIc65e2/LuM8WYInBGA4OvHGN1FwZK6VSfH0SRW4ZBWAHReUwyvPB/B4U3cWA3TMTGyKZ6ArGzsR81IU22q4qoSX+8afUiMjEEgucQZjlOU58xh/EA1Cr5TtWdxnumdJqHi++BYzWUVr8+KPMli6hkc+dQ+fn3yiorWREpRto2no2gd1EDIl/uq2pNM3GT2Rz
      AZURE_TENANT_ID: AgC7B4aSEhG07SEGKD/+jryf7HIDeG6wUPtlXDgOmiiNHSRd0vxOeg8WcS1KlWxp21oYho+4sgUidRL7upNtt9VujQ4L+Qfz2IX0I57y9GgI0yQZdHqWrpISV5lzPDn8aHyA9EDoZkCnAuMrevbhp30/szcbPDYt6NCiphp4T/mwN1WqaY7dsFnQ4mItUwLyttI42JpI5hSZrCYnTPLY+BcC2a47leZg2J4juZzsaoq3qo14LPz0ekj3QPxqRwqeez9yls8D4ZqJOdASCFI5TPgeABcIOv5uzM5goI6Y5ejSXYTsqeuaDO9sxVo2xOG8RcKR86HbNzmwhk9l98/+fZhdJQEWtvXdyOIuwQw5Mopte4hEh3bYn8BGKPM2br4Bi8h4x2TZByw3zx2qEFwPwBTOdMLY9C8+vqdRFB3pvw8+u7jlHVx3KmQ88dFF2KmvZunbm5EZGDrR1+7+/K5B9FPZnZveUdDEYl3UYYd8Exd+WaO1DeTD+xb9pUFhNxj31WO4Bwo1PJ7ZxyW5kO/WVu+GaOGHXOEczmcAnlPhhghw/nPDr4YT70CKFsaQ37xrw7hu8xuL/Hntr1EERzyEAv0N/eKfr+igVvV8IL4RTTDCKbF/wsPmx4tm2FJDMHc/ZG8O4Ew39AYAMvisJrjdnnmMQxyxV8v86UFtKEnKPyuGU4mGNbcOHv1p7roaePMm+aGFs2aNtD3GZ8LlUwqpNvPKDdheAWPvBFt95xnmEDXrGmOWwq0=
      DB_NAME: AgCuY1APiwGfXb2/dp1do5DO/WhYR/R7fnBqJpssHIAaV/tDRMb6mzX8oncyj4OTZxKnvizqBfPyh0SiKq8pEn6s0LXt2w3Fpdt9TYJPZM6f+htX2FsCc9+854Mkb1BbSZQe4ES34HxeR5a1QQJD8fIZQPnQhSM+bwQ43eeg7nnief8gRgt2LeJEDRKasreCDs+vE2mFZKorpuof5rnnx2AcrPsltJQb5lhzJccOm0eFRCZH4dHzU4FAciPnzgRVwiwPTqST7xyjt/mM4ycadjcJ2bGUR2JtgqeEJ6DrXrTo44rx3+R0GD85bAzTkkgzBATD/ocqZc7jOPIg/9fe2cxO5aRQRksCceUwChHd8U/vNL9n38tScRjEMv0giVDgD8/QQaCslH3XDwnct99/10uFhhqbgoW9G+UNgEX7opSKjyOmy+WI196LmIxVzxxaDSS9ZEBdFH6B3VF1/XWW4O6O1zJpgg8qM6tw6RfQlFjdpip8ncUujUYY2oxY03ykrm/fp61oH5vhxqnAcv96/DNs8H0aY1U9pdsne+ogvQCaVFti7X89Aew4dpEgdykWhhjVdQF0aTgfrNZBqpNYfNpjvuyKEmGBz9A6WiWh4w5/07rXwfP6QB5jKI71u8kykJT0Xa8xMIKTBqSUQhDTuRXRtP6Cl44zDGaabOx3o+38hWOw6unkcJmEQ7gJvsRA30X8VzDUWB41Cd4DeUKo8R6yjIfHZaiIxbA4c+O86I+wcTS8yPR9dcOA3guJpjQCrCXwhthU8Lw9pSif35N4kBYUPvjmRA7Dxy5B3tHPGaBGkVXnbMkeqY2arV+roNSuSaAZkKFrhOYn
      INFURA_PROJECT_ID: AgCYCYZKAA0IL0ys1HOGQ+d2syCwp2dWbN1VyUEROCK51JZNpVq5r8mqzPj1cFQGitCnzphxXCE6D0fCn1hq8heoKJZaL4lKlNdZk0u393m0W02gJcVRAI2+UeCgjMXQf4I9Qfo7SXQqAFnx8hYFsb/Hm2PJ2IrrapALhO9/4uVQvaIzFiZ5nnZLRIOZ7YUvQQBQXRooKLwqTkT69JFrvYTRwVUwRM93wg55Fx5PPzK87EkUftLUIQj7fTpNH0ZMmNvNKmCAshdT+IlJU1CYRiqOBuUnSJmuX9WfD8vZPIMNLwgk9z+6PPSoQM3rb4KwWataZ/TI3EDBG6M1CmKEyvuFfhuQ/VnaISluGciHErYKogM3RcxbIKvfUeaFAfFGXAGdGxMd0HiqjAgYtGOs1qGayngMczfqZZ6ACj0mVplBQ4lF0mCRw2Vxtc7P+22GKGemGZtdOdP0GJwey0Vgmw2PM2pWGOGOcbLMPyME7ewE12W5bqLCLWCWYWCkmqNVMOgVRP3UJ0LHY4mg+N06huypjsrhLCdIdJcpyJZv2wbOpKO/7bSYpNP1XB5ZfNRFinyyUAiu9R0r+wRkSrI8dYS1aod90mB0zRqtVKMWmOUS3U3QHepDl5swQOVmhdO1SjDoEqroHUMrFmZyWMh5JCkAfcfqscuFxdckSFQ062xmFa3FkAbsfhfNQhVxVP7J4mg/msuROwgybzqZbl9aCHY/zYo9HDDCE05wzec=
      INFURA_PROJECT_SECRET: AgCkZdoEDuvmIxgGgPJ/c8RBVgSQZRQ6cThdYYWUSLr1iZy/052jgAm1fYqtBQ3f9fyzUScDoiF7uSz16GfVh+uc652JysXcUo5xZ61VEQdd137CnyWTKo7qznT2BTNWKEjKGSb4SdOQkIF4QHxedK39BPhx+nuoxCL1tt0tfdo8hQ0qPIiaNPNTd4erwAOClwXxOFRT0XbHRJp6iQU8Bab3rzFPgGoVMMm/uH8xU+XzT69PE++PNPZASThekzkeFS/g+IWZa1R5nIDTQFeRlcvmF5mXl9FeaPvJ7hZRUpsxZ+p1frjJGTKwCvdH1U0OS0Qdizyptgl7Wrm3Q3g/G2U7CPfmwV1bM3EDoCjrlxTYOwc2IzNPCGN2yftV5XF0N6cwLFhEev+Hhsdl8zP/5JOvM0NgJUFA5IeiTdFdw1OIhQCxP13fIbQ66BtyM3CFEspe6JClRhCOJVG4wjCoDp73/BsEDOBLR5OP9FV57+nOhcW3h0DgUhmKAb7OMLH3velN9WNLelhOcC6fEjtVtf/maMV4C27xp7Vb1B7yjzVXpKEz4dUKAO1KpFZOqQDZRyx+lAtcfRnMdMAgazM4qMAdTBB7jQhVDcvGkvQNIN7iWwcjxKBySIcIA+meQPfhutP/yZEvfA2BWLfWUifTyhzqjBZJRf1CtHztNCFawVq3XGzwDnhsQqopl7jl+oN2VO2QYsibLkEq/8KjW1TYgYEK6My0VQtUkBxoA4LKbpzgsg==
