export enum Queries {
  Namespace = 'namespace',
  Owner = 'owner',
  TopicId = 'topicId',
  FQCN = 'fqcn',
  PrivateKey = 'privateKey',
  MessageId = 'messageId',
  ClientGatewayMessageId = 'clientGatewayMessageId',
}

export const routerConst = {
  InitialPage: '/',
  Dashboard: '/dashboard',
  GatewaySettings: '/gateway-settings',
  TopicManagement: '/applications',
  Topics: `/applications/[${Queries.Namespace}]`,
  ChannelApps: '/channels/applications',
  ChannelTopics: `/channels/applications/[${Queries.Namespace}]`,
  Channels: '/channels',
  ChannelsManagement: '/channels/management',
  Channel: `/channels/[${Queries.FQCN}]`,
  IntegrationAPIs: '/integration',
  ClientIds: '/client-ids',
  LargeDataMessagingFileUpload: '/messages/large-file-upload',
  LargeDataMessagingFileDownload: '/messages/large-file-download',
  LargeFileDownloadChannel: `/messages/large-file-download/[${Queries.FQCN}]`,
  FileDownloadChannel: `/messages/file-download/[${Queries.FQCN}]`,
  LargeFileDownloadChannelTopic: `/messages/large-file-download/[${Queries.FQCN}]/[${Queries.TopicId}]`,
  FileDownloadChannelTopic: `/messages/file-download/[${Queries.FQCN}]/[${Queries.TopicId}]`,
  DataMessagingFileUpload: '/messages/file-upload',
  DataMessagingFileDownload: '/messages/file-download',
  MyMessages: '/messages',
  SentMessages: '/messages/sent',
  VersionHistory: `/applications/[${Queries.Namespace}]/[${Queries.TopicId}]/version-history`,
  ChannelTopicVersionHistory: `/channels/applications/[${Queries.Namespace}]/[${Queries.TopicId}]/version-history`,
  WS: '/integration/ws',
  RestApiDocs: '/docs',
  AddressBook: '/address-book',
  MessageInbox: '/messages/inbox',
  MessageInboxChannel: `/messages/inbox/[${Queries.FQCN}]`,
  ReplyMessages: `/messages/inbox/[${Queries.FQCN}]/related`,
  MessageOutbox: '/messages/outbox',
  MessageOutboxChannel: `/messages/outbox/[${Queries.FQCN}]`,
  MessageOutboxRelated: `/messages/outbox/[${Queries.FQCN}]/related`,
};
