version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=ddhub
      - POSTGRES_PASSWORD=ddhub
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  vault_dev:
    image: hashicorp/vault:latest
    restart: always
    volumes:
      - /vault/data
      - /etc/vault/logs
    ports:
      - "8200:8200/tcp"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 'root'
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
    cap_add:
      - IPC_LOCK
    container_name: vault_dev
    entrypoint: "vault server -dev"
volumes:
  db:
    driver: local
