# Default values for ddhub-client-gateway-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ddhub-client-gateway-api:
  replicaCount: 1

  clientgateway:
    config:
      # -- The URL of the DSB Message Broker you want to connect to. Trailing / allowed.
      dsb_base_url: https://qa.der.aemo.com.au/ddhub
      parent_namespace: ddhub.apps.aemo.iam.ewc
      secret_engine: azure
      # -- Sets the secret prefix in the secret engine.
      secret_prefix: "ddhub-pxise3/"
      node_env: test
      opentelemetry_enabled: false
    scheduler:
      enabled: true
      image:
        repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-scheduler
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: 1.4.0
      appConfig:
        NO_COLOR: "true"
        AK_FQCN: "ak.enc.pub"
        AK_TOPIC_NAME: "associationKey"
        AK_TOPIC_OWNER: "edge.apps.aemo.iam.ewc"
        AK_TOPIC_VERSION: "1.0.0"
        AK_SHARE_CRON_ENABLED: "true"
        AK_SHARE_CRON_SCHEDULE: "*/1 * * * *"
        ASSOCIATION_KEYS_CRON_ENABLED: "true"
    ui:
      enabled: true
      replicaCount: 1
      image:
        repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-frontend
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: 1.3.2
  image:
    # repository: 098061033856.dkr.ecr.us-east-1.amazonaws.com/ew-dos-dsb-ecr
    repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 1.4.0

  imagePullSecrets: []
  nameOverride: "ddhub-client-gateway-pxise3"
  fullnameOverride: "ddhub-client-gateway-pxise3"

  config:
    enabled: true
    secretRefName: ddhub-client-gateway-pxise3-sealedsecret
    configRefName: ddhub-client-gateway-pxise3-configmap

  podSecurityContext: 
    fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  
    hosts:
      - host: ddhub-gateway-pxise3.energyweb.org
        paths:
        - path: /docs
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-pxise3
            servicePort: 80
        - path: /api
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-pxise3
            servicePort: 80
        - path: /docs-json
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-pxise3
            servicePort: 80
        - path: /events
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-pxise3
            servicePort: 80
        - path: /
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-pxise3-ui
            servicePort: 80
    tls:
      - secretName: ddhub-gateway-pxise3-tls-secret
        hosts:
          - ddhub-gateway-pxise3.energyweb.org

  sealedSecret:
    enabled: true
    encryptedData: 
      DB_NAME: AgAEWMDbXN7mD502Oixfl0uYg8x/4aCIlrY+3O22iLdRHyzBvdCgenZDZT9Ne5mxu+3Pk/nysfTYEa8RgzHHSvYNLEQhhD0v/JilMvG6vYWCBHwDopgV8a/p1u03956GV3aWLhWq9S8uEYLc77t9ebvmxsaVFlGwMhPZrOeEwJ2q4zxJqpAZJHlSI6WuLeUkUFlIMJ+B/RuqlJXKopMZymM5Z/UlybRDoW4GPDF6OzCIHONGRtEv6yRqyFdN2Hl0qDd3W37ylyx16zBYyapGdmxNeLhG7YlfjekLDZSDKWdtZ9Q8wM93XJKvW3arzjdUQHX6KYexKjCprOH9rqZxyeVoQr1udEGg1GGuTsCT6kE9YRYrwkloO8Yo0JCaszTpHLbs3JXSX/IR8NlCtx0KfBj/obuOcWYlMIXsR6qww88/UyRecRYIR6+1YOE3hjgE5vBWUUdGRA7KJt1YkYEMNqIQXu+GBN3a0Lb0k9B7blWFCwUBLxi5VzxhTwbaLcbCiC6+xqXh21LI+XxhB3goLeFovXVfe5Cqz1os6rVaT4V7r/UF3U1EMVI1MnFgb4aaln40q26vCTzoxs7KglQWuj07xbliRM9apErRYhcuSH4yBKhDg8BtRYz3S++E/oBEZw4qU/kuQBBCChWioELsYQdcG4xuv3uEq5X9+9PVplXQmgbuTTE4E1FMV24rSvxzeuOUatOvZOtc0mYM4DbUiNt2MVFwJrXFXY5zM19Qwjt3g/H5+edXxB41XbV5k/1YZhzd+lTJPOyHc+qvAdtqMdkdRnYUUm99uJkzKj5siQO0CLogyCX36E2wYC32t5Ljyup6xvJOffUqoP9S
      AZURE_VAULT_URL: AgCRx2opa5N++T5PQtzUE7iGyQLEeALYw5P3KtfahJZG8+Quw+k27RQLAKbEPKumCgyeYFJcwcEenZJ8OhUnpyJ49pN/9deSquxB0I96hx/4dgYwtL/V17bcCNEmC6KX1cPijajj1WfGS4NA+JgF+jzzqQgQEa6c6DebeCs1Wk93Q86UNq7nAIZ33MFRKxH/2AR6Aeq8A5IqVrBm5JWONppOGXJ6UpbkmIN2Uag7kOSOVqWVMF+RIlS1h1UWDV/Qwj2g1DZPfd+h/lWzjyIcArjvTbhYv630CgT09H2G1spTZc7gwHjtovoCUlumSPDkDvAKauPMM6PNCJFZeZTD50151ku7cj1EyOBsyhJj0DVWYKnB3SS/9NiIVUk81+qZdFkKgMv+Qqn9fExnH65i1pJd2iYyeD3Lgr5j7WgyfWzGCrS/Avkfp35a9X+EW8S3LC8MHkYOS0LPFSDYFwSsMxZqQpAOJ3mT3ZJUdeBik0iLib6/Sv9X80bh/nAzCSIpKxNvHDcKky9bBE9KiGx5JNZ7W8XErmI1X7acpyz5iX7NFNExkbfTc47HPse9hNlvSXklCQo2EeD/179BxyjVzOLN166rVjh700qSVhqN5r4m6lxaI4YQo43+0/M2ad7ySyUX6DWZMTIwqliHQiUlkdiA6Q3L1Yi/QQqfAa2LbIlddymGGW172WKBnGuT4ItuKuRuXfnnRgLUnAnsuxQenGJ+MEZuSwgIeML3rnXc/+GNtL7rf0ej/A==
      AZURE_CLIENT_ID: AgAODQpD9aziBY26fJWyq4Sbj61taT7TRk4dMN772/ih6lL/LGGwV+Tcr7gGT9Z8D5Y1MNkVGNT1PdNP2PX9FkdWPXO5CRuspEVlNnbs9apzCjIUbmQCMd9XjwWWw3nrVooYA7vJMlQqs66GMzE2BZcGE+u80ZVB0i0IutMDvFLkZP6SP/O91SLxGIz+fpLQEUeoE7ebeRGgJfhB/05177c3T6OrJKposYWRHWYyurT16mZWJ2noSE7lpMylumqB/4YG0/C8dJtLD5kRON4scsbdKrk7O/iNfqoi2HcVROZ/cRr86gxhMEqGUArSVy7J3opyx+fvieVqZBGvPDiwNXhWgicjxv1hcOOMz8DRjlWsg7NLNWRG9tO55XZp5FBTSdgO7kYGYNZVzcarRXPa5642uRdJ50/1p5EhChqk3+o6u7QorIn6Md6qObHNqW+oYBbnatugQiecvGwjNETqnFL6Qc5EnzwDZRhOEwWScDzqyM1LN2jWpJRQTyaTF+Uj2dFlAXIjQpWBbSAqGFoC0z4DrMYFy2G0gR2ew+iytqlBjZLBFXJJA+DRWI0yKCnTnW6agegO5UmLi77UUohX5CDr5uz6s9l/K07i1iHaeilX8yhviEi0o65ZbDOusx/NyuRg5RacWwJBW/lt+DBiXwSlfvfm8gUvjAdx0KTnn0NHV7f0XpkMvqJEPRlXOxawqmqCJ/ZAtmDiRcWHkpLsRGukyZA97GwbLcYVbCrQbM9B72hATvo=
      AZURE_CLIENT_SECRET: AgA4f6lt379Kae8WbBO9vZNqENc27KglYMppRwq+WmBtDNwFEgcONSqkwbG91JlH3zM8idWL1GX+EtcVnxvfJXqSNSRQrNW522m5LeDb17dIYustVW344AmEVbR6sinrkYPHL9peFTOm+Hn/id6viQGnC5fs5thjsPVMMfq9ZOPZWtCiWzXHbms3RPyC5Ro5l99B1PpPhTrOY6xlpQcsYywp4X8XLh9WlvHx25iOC5SDJqgVX3GBrfEY5jAt+nWUnWfSx7AVceSjReIlmNmCK07eA/BOxSBZAKSPKCSCY4yFlAHEsRi9ywI2kcHSWUb4R2Z9qVafSaLhMtcb03wtG6Ttd9SJ6NqStmg9x3EHhDIU3BgmdiPvF11W0kk8Ar/z+tV4Tc4IX2hdsg38bxl6UrXDhP0fUnZS/+lC0CqwBUkQFhdSWkBJrWDWizTw68qhtdsGNDcVttCQYbdj96zDp/56iHn8t2ni8V5pWIyFiOh9m29G3GCf5N5F8+7iykYu1TnsZqaz6gWnGuEjMUlDiJFtAKd9H+2Me4V2dQJ5Xuyr474/w755iF7Tjkn/YBjdc5w0SU3CwerVu4IdNjvSvN9YjfDe/6l95X09+PszVds9cnIvZXz5j2bqMMl1tgjHEkP180bUxyXDw6gKWacroLTypeidqpF8OGJF0x9T4Ynd4Df/QL70+GGIZrGkAHjW8N6qqw/bPOCWuJhFnNF57KFvwDdnJ9v3px8TjyQCeCtLwRNd
      AZURE_TENANT_ID: AgBWjQmFO0ap1PjVg+upJsGawxzuffJDB+yYoH6Z39Y501dHEoiccTWy8vvDIFkpS01BlI/AgMMdkzNHfZkaJJGuaBWgjDM21TEXv8qkz30tymC6w4ydQQgZRCRg4ZOHRSNjH+rMp7i6Np6AtQcvfvYY8xUYcH8AW7Dn96mz9+C9Xbj+EJtRS9WhejnWuyDfKNj0scq+4Cn8wiQqsx8/9wi5TZJmbhU83rD/iM4L4ksCBF7uCsJzCZPV6G16qUX5zrz9YROmD2C8EZszEuBHbziL6gUtiAi1YATEKmxaYQp3xEMIzd7/OmB+wmT4VizWQqQkzVkidfTRTDPtQer1oafiEdDA/JDL5y6gPrxMqjHK1ZLLuY7yGCiwzZL3VpJ6AAiG/3pjgHGNQmm1lha18J5x8JI/5T+4p+5/N+jLXsafmpL+1WMlmHWpv0qQB2KwqFI3mw9aabfT7eBBsPDqti6EHC29nNVe5klhrVptyMjtko/JEhvrPCr24SUQgXBk6ZRQyUClYh8KQvnXFP0DVhzbdbyb3JVIrcd7eT+Z3KHOXQa58ww999P0BQYWPWDwkCqh52WRkA9rWCwk7sMH0z/evDRmKxQ84+zxhcZQdyKcCk2Ojt4aj7TobW5R2RV891tYnWqM7pyg8bVqTlyb9dfcvV++LSBKEVPQdojT3AINekL1rT1Nxj8yhIzaG3BaPmMOYdqFGgNHZWoDwUywpCBa7fcNzi0FW0+ClwdVJ3iiA18xqlk=

  probes:
    liveness: true
    livenessInitialDelay: 100
    livenessPeriodSeconds: 10
    readiness: true
    readinessInitialDelay: 100
