ddhub-client-gateway-api:
  ddhub-client-gateway-ui:
    enabled: true
    clientgateway:
      config:
        # -- Define the port the gateway will run on.
        port: 80
    image:
      # repository: 098061033856.dkr.ecr.us-east-1.amazonaws.com/ew-dos-dsb-ecr
      repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-frontend
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: canary

    nameOverride: "ddhub-client-gateway-ui-dev"
    fullnameOverride: "ddhub-client-gateway-ui-dev"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: azure/application-gateway
        appgw.ingress.kubernetes.io/ssl-redirect: "true"
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: ddhub-gateway-dev.energyweb.org
          paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: ddhub-client-gateway-ui-dev
              servicePort: 80
      tls:
        - secretName: dsb-tls-secret
          hosts:
            - ddhub-gateway-dev.energyweb.org
