# Default values for ddhub-client-gateway-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ddhub-client-gateway-api:
  replicaCount: 1

  clientgateway:
    config:
      # -- The URL of the DSB Message Broker you want to connect to. Trailing / allowed.
      dsb_base_url: https://qa.der.aemo.com.au/ddhub
      parent_namespace: ddhub.apps.aemo.iam.ewc
      secret_engine: azure
      # -- Sets the secret prefix in the secret engine.
      secret_prefix: "ddhub-pxise5/"
      node_env: test
      opentelemetry_enabled: false
    scheduler:
      enabled: true
      image:
        repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-scheduler
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: 1.3.2
      appConfig:
        NO_COLOR: "true"
    ui:
      enabled: true
      replicaCount: 1
      image:
        repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-frontend
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: 1.3.2
  image:
    # repository: 098061033856.dkr.ecr.us-east-1.amazonaws.com/ew-dos-dsb-ecr
    repository: aemocontainerregistry.azurecr.io/ddhub-client-gateway-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 1.3.2

  imagePullSecrets: []
  nameOverride: "ddhub-client-gateway-pxise5"
  fullnameOverride: "ddhub-client-gateway-pxise5"

  config:
    enabled: true
    secretRefName: ddhub-client-gateway-pxise5-sealedsecret
    configRefName: ddhub-client-gateway-pxise5-configmap

  podSecurityContext: 
    fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      cert-manager.io/issuer: prod-issuer
      cert-manager.io/issuer-kind: OriginIssuer
      cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
    hosts:
      - host: ddhub-gateway-pxise5.energyweb.org
        paths:
        - path: /docs
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-pxise5
            servicePort: 80
        - path: /api
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-pxise5
            servicePort: 80
        - path: /docs-json
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-pxise5
            servicePort: 80
        - path: /events
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-pxise5
            servicePort: 80
        - path: /
          pathType: Prefix
          backend:
            serviceName: ddhub-client-gateway-pxise5-ui
            servicePort: 80
    tls:
      - secretName: ddhub-gateway-pxise5-tls-secret
        hosts:
          - ddhub-gateway-pxise5.energyweb.org

  sealedSecret:
    enabled: true
    encryptedData: 
      DB_NAME: AgAuTgjQZa/cNolRqGAmryA2yJ1Sf8Ih3B3OK9cP8FstvM31Q4+uNlqvEcmSuRkxZMcIiISl24FESyDdJBW37P+kApikquxJvPcTLZ1/BCwvoTGxf0VHYtEkbzdScmzOWSvIiGxdfdP/5duSiEzUw5SVb8jl732/GnMFFjf/Z3ymwNQvauCuKk5qE4cG2zI9u5Ql48RuMVxAY4hoLYK56+t7MPuwTWvtlgVlF3Yyddr7okPePti9hrKsQqG58ZpQwNpiP5SlfdYj/FJ5D3V9XpVL1GfEdC4pwuPq50Qv5bBaLhDczcvCZB+oAg9B3i3gMrMFdP8FLxgRVbBWiC5cHUA8N9GsUTutHSIwsB8MZmlQcZlNG2+w1kFIPtpQRf2qvj6b7vprhMxw650MERbQjmMnVpIvHks5z58rqwjemmfRhugSY38W48utlrePeKZrm1dJDMIYsEQn1sII32fYqYkwxWj5ChRH1tHmlBuVneqHUZr9/zzF1CS/K7W+MPKx3aM3P2YLYvsQfnSlu23UFGxawELdFkkJF6hpPaAz1J8UnBW9zGVrG0lilZRZuuLE8ClxNB20xbVxo04lYZ7euwUgsrnBDdqckPw0xkl89Ev1pd212SnARiYz+dBf/0AUs6fa54zJJkWBdMDzGpPgzS85SqkKmV34mPO2rn0nW7L1s1h7VbmB0FNxINCsgwQtboqAwqAmVu4eaET2bTl9MMq2ahsoicaeA9gqU4Dzf6lE29Uij1Wz1E8re6q6AA+H2Gt3vNpUsw8LrysxZdqJJUIVRld4M2yyi05Il+0cWk9iBUTLWpt4j8ZUnTVRA5dlBrP7ztQknsL9ars=
      AZURE_VAULT_URL: AgB9P5yXLWRb3pJAmaDKqvFyqcXzu08fLsjE7ArcEw62pkqQUS3l3+gy/yJKjZHmgZXbM+vojMM5kapAbmiqweX7HVzbD0ORPUPgxVNHFs/AVSKtKRms2FdwYokwZuY4CEMwzdrFi2c3DrUy9ISxNOq9cN7v0fZJwIah4dMT0gTfLYMNVY8uStS2lzeTn7/ydp/F6n/TFBNMKJmAHLMUpUOHWjb68M3w33PB8XGq58Rek0WRvR+Q6offme25pVVour8MRDGo6MNfP9MtvBOaKdqkGXiq4yAviCh0Mbn2yb5ivjuNOJMoMUH8Y+JDJdYJ3y7OcgSC3rBAAdIOGhTOiIWhCy1RA46ms4XMq/72gO4vy506cKOuBDUHBTA9UTqWx+Heg+Pc0sumyeH/S3zQwk0mbxpwU03gJJlOCsG4Lix2K/dQAMvIPFW7b01xQIcsO+7nS/eZfDC+hRh4H4yWs6r2vZYfglpYYmdoEMUdRvHMBDdH6u4KYEyUScWdgpgHlQVU+PNorPqgamqzJpkkPRpVjoEqiuHNdbhjyppi5OC9tatxHSzxpAXoa3Ay5UOcZggCeGRpq60AHdn/Ge14MLlnwO10Z7fJrfxR7omBNk2RZS3IPMeduq3N5JT3EK+tSH2o88hHMemTEflC03bw5oJLpgHnV2KmBYVU5L7bNNSGpdFeawerEwbcwvZM2GIF0YIuYDNeugr8SXmg73jXktTS9Etq4Fwp/rOmk+QK+d7229Fd8clyLw==
      AZURE_CLIENT_ID: AgAHU5Oj9dhbexGwbrVFWkZoQFJ5KfOJzQMljfHf5ETzSAw70xcsDKGdnAl2xq9/24KshkAUZhgtoH0mgpzgp0OryJau4l14nS1aXNOYWuz2wPV7hyrO7DTLjcz/T0r14AaGiqZf8QaLKvLgJJVWGVc5RJ15BHi5uq4uwTAiZDD4U+KeB7nBa4Wp/H22nJG8TfpHlhsVxVh+fNir1oulrHwWiOTQDQzRpgb5miKUh8ishpy3D0pnbuSei76syW+Aov3ysZpP3xoV6VuFzItNwbXZlT4vGZvqsubKIkzEFYmO6q34j6cvLxZOU7WtkJbJMDkhxWl3zedDq6SLZnNvzFRk3GiqxcoI2MQzhIC3Dsmzapc6dXFiaKP9OuX74u5j+L23XlQ9cqbdq6lw85XmYOa/J7f08olXwJhAN7emU/9/Vxa7yhdOwrLH0B28Szdlf1wx5khNxj3pCxk4DS3ql84ArvJBJLIUia8EN61GX7/H2lZKGjNSh2Yt/Mb0nXprHyB7S2C9NhYNxVCURy18hvSMC6p3xLN/Zb/AZScieqbNoxOLvQlHT4p1JRwzb65GyCkFTkqw70qERItJl52d4YTQYOdT/SKZMNxtiAveL3okZcLfX3BsjgxdQ2D0OYn5lFPdkS3BPeKl4VDSpfLbZBqVcztjeGm64FXVS1SmsyGoh61xqFUf1Ya93/XPx4gqzo3TvUkWH727Yf0kAwgiIuk2VQfTybg0HcpkiLaaqHkHmoyiUR4=
      AZURE_CLIENT_SECRET: AgAZt2UDEO6klFYTEelIUkiIYLSMf7QsbDkL1lWVHp+uIP2+gx6GSRas60UQrsrjDNVAABy2UCEGZ4+zcusaAc2H0Ojfa0Ox3La68+DthUVTiv1sDfQPsVvRwgMhHwSs4+Hc3YNjzO7iwFy+b2NuxTWevOuKvQgKZ5xhfi2CT+MvqaOP3t5eg79gKCXMcy6yWu6GePzv/hSYqGg/8C79Egt05ZrpbTTloWT4EIwfkdmI4+3U17OTRB/0nW/PcHHMYUMgwDkreSLDmkKGLMtfIkv9Bg+DubKPlN3MgS/PwxX4jeX4cXZQiXLPdLPVTlR0BqsvX7H0IT69VRhrpb0XX93gZiNRYJc26HZ3RspdOV/XmLx+zg7Ze7UG72BblSGH1e3KvnRPvrV6ja2BaqdJ5QfvCiKUlJqB1UPZrBFkD2gSvr5OYJk1RYlGaIiuFsJW6VjX7qv4LYhxmIKj2butyRobEIXJQENiVQx/M0qXw0OeAg8naQ3VSFh61YElG1AkSwYXABKXWdXEKFZu6YwpN6+qnlJtT+n5FYJO2T/FqJaSq/4NO8e08bPfWshvwgExC2yNLqZC9Q+YOkd+43AX5mvrj4G1XvzVEdwwclnEl10MNlYnaIgUr0GB2AfUfsafCS5+cj6dh4vukj36LV1G4uXEeL7BD672jgAmkYs3pNe8gZ1iwQmMEmy7cddUMmp3J6lGk0OdX/Ec4QMyWXBj8SqCc6G7emKG9OPNqRsR78f6bmKj
      AZURE_TENANT_ID: AgB/5qySaz495lTTlENqqiA5tkuo1i2SuxnGh3dNjg3JnShpwnzqQGm2c9ZykPSwgIJKL63r4zGRwzajFTA9BvcRXJvV0Ib84GSNzRaft0iEHfSt76Xmj17fONRM3PSXxDITsnvOb9Z9dEZ98hYjETBYi9piry9jswlc/OR/hF6SCPbZijOnqtsd/Yg6PopvfgEjXLFX1pBh3wJ5zwVkH1XiK2C/3kAZ9lEhQYReVAbK15bntXVkxVsBNrx6nmVhKa0aP+DyEOv9q3X+TF3wMWgOCp88/xe8msytawzO5y4Ll6QituwDYgcquYgvZFA+8cm5ff9Inqnechc0ADM9jZsfcptvl1I4ygtou/a4WRmayXRM9mD0B/ChS6EizwKDThjslVXLGcQvEzVIprrBrGRCsml2vsl1HfHR2I2//qwKwImU5iypvH4fSGBcnf8C9DVkOQeyQr5iA90lQtuuIzuljDzZ/9x0v+WsDahgF3zU9sL1kmOvBTA+V1GsYPkMFq7JU8ZVZQWvj1cEUr/u4hfSfHi+1PHWgCto0b1KMxR7Ep1HH53RKDKOvGtTsBPg4gUwfDfARZjLMHNOsQ+tx4jt+a2K7OP8vCOFJ8NQNNtECGMA1VM0QwJZHdC5qFn/jSGbGjmuB0U11oL0bWDltFwWovWpGDg7K1RUX/Ta/46vYM2nOOKoKe87vS4DBhpaGDUCiFXxOM21boNhIViul7VNdlG7A16/NTHDfCEoj0WfPeBe5Zc=

  probes:
    liveness: true
    livenessInitialDelay: 100
    livenessPeriodSeconds: 10
    readiness: true
    readinessInitialDelay: 100
