version: '3'
services:
  vault_demo:
    image: hashicorp/vault:latest
    restart: always
    volumes:
      - /vault/file
      - /etc/vault/logs
      - ../config:/vault/config
    ports:
      - "8200:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault_demo
    entrypoint: "vault server -config=/vault/config/vault.json"

  vault-init:
    image: hashicorp/vault:latest
    container_name: vault-init
    depends_on:
      - vault_demo
    environment:
      VAULT_ADDR: http://vault_demo:8200
    volumes:
      - ../config:/vault/config
      - ./vault-creds:/vault-creds
    entrypoint: /bin/sh
    command: |
      -c '
      sleep 3
      if vault status | grep "Initialized.*false"; then
        echo "Initializing Vault..."
        vault operator init -key-shares=1 -key-threshold=1 > ./vault-creds/init.txt
        echo $(grep "Initial Root Token:" ./vault-creds/init.txt | awk "{print \$4}") > /vault-creds/root_token.txt
        vault operator unseal $(grep "Unseal Key 1:" ./vault-creds/init.txt | awk "{print \$4}")
        VAULT_TOKEN=$(grep "Initial Root Token:" ./vault-creds/init.txt | awk "{print \$4}") vault secrets enable -version=1 -path=ddhub kv
      else
        echo "Unsealing Vault..."
        vault operator unseal $(grep "Unseal Key 1:" ./vault-creds/init.txt | awk "{print \$4}")
      fi
      '

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=ddhub
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=ddhub
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ddhub"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ddhub-gateway-migrationer:
    image: ewfcontainerregistry.azurecr.io/ddhub-client-gateway-backend:intelligent-canary
    container_name: ddhub-gateway-migrationer
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./vault-creds:/vault-creds
    entrypoint: >
      sh -c '
        export VAULT_TOKEN=$(cat /vault-creds/root_token.txt)
        echo "Vault token loaded. $VAULT_TOKEN"
        exec ./node_modules/.bin/typeorm migrations:run
      '
    environment:
      NODE_ENV: test
      DSB_BASE_URL: https://ddhub-ewc.energyweb.org
      RPC_URL: https://rpc.energyweb.org
      CACHE_SERVER_URL: https://identitycache.energyweb.org/v1
      EVENT_SERVER_URL: https://identitycache.energyweb.org
      VAULT_ENDPOINT: http://vault_demo:8200
      VAULT_TOKEN: $VAULT_TOKEN
      SECRETS_ENGINE: vault
      DB_NAME: postgresql://ddhub:password123@postgres:5432/ddhub
      PARENT_NAMESPACE: integration.apps.intelligent.auth.ewc
      MTLS_ENABLED: "true"

  ddhub-gateway-UI:
    image: ewfcontainerregistry.azurecr.io/ddhub-client-gateway-frontend:intelligent-canary
    ports:
      - "3000:80"

  ddhub-gateway-api:
    image: ewfcontainerregistry.azurecr.io/ddhub-client-gateway-backend:intelligent-canary
    container_name: ddhub-gateway-api
    depends_on:
      - 'vault_demo'
      - 'vault-init'
      - 'postgres'
      - 'ddhub-gateway-migrationer'
    ports:
      - 3333:3333
    volumes:
      - ./vault-creds:/vault-creds
    entrypoint: >
      sh -c '
        export VAULT_TOKEN=$(cat /vault-creds/root_token.txt)
        echo "Vault token loaded. $VAULT_TOKEN"
        exec node main.js
      '
    environment:
      NODE_ENV: test
      DSB_BASE_URL: https://ddhub-ewc.energyweb.org
      RPC_URL: https://rpc.energyweb.org
      CACHE_SERVER_URL: https://identitycache.energyweb.org/v1
      EVENT_SERVER_URL: https://identitycache.energyweb.org
      VAULT_ENDPOINT: http://vault_demo:8200
      VAULT_TOKEN: $VAULT_TOKEN
      SECRETS_ENGINE: vault
      DB_NAME: postgresql://ddhub:password123@postgres:5432/ddhub
      PARENT_NAMESPACE: integration.apps.intelligent.auth.ewc
      MTLS_ENABLED: "true"

  ddhub-gateway-scheduler:
    image: ewfcontainerregistry.azurecr.io/ddhub-client-gateway-scheduler:intelligent-canary
    container_name: ddhub-gateway-scheduler
    depends_on:
      - 'vault_demo'
      - 'vault-init'
      - 'postgres'
      - 'ddhub-gateway-migrationer'
    volumes:
      - ./vault-creds:/vault-creds
    entrypoint: >
      sh -c '
        export VAULT_TOKEN=$(cat /vault-creds/root_token.txt)
        echo "Vault token loaded. $VAULT_TOKEN"
        exec node main.js
      '
    environment:
      NODE_ENV: test
      DSB_BASE_URL: https://ddhub-ewc.energyweb.org
      RPC_URL: https://rpc.energyweb.org
      CACHE_SERVER_URL: https://identitycache.energyweb.org/v1
      EVENT_SERVER_URL: https://identitycache.energyweb.org
      VAULT_ENDPOINT: http://vault_demo:8200
      VAULT_TOKEN: $VAULT_TOKEN
      SECRETS_ENGINE: vault
      DB_NAME: postgresql://ddhub:password123@postgres:5432/ddhub
      DID_REGISTRY_ADDRESS: "0xc15d5a57a8eb0e1dcbe5d88b8f9a82017e5cc4af"
      PARENT_NAMESPACE: integration.apps.intelligent.auth.ewc
      MTLS_ENABLED: "true"

  proxy-server:
    image: nginx:alpine
    volumes:
      - ./proxy-config:/etc/nginx/conf.d
    ports:
      - "3009:80"
    depends_on:
      - ddhub-gateway-UI
      - ddhub-gateway-api

volumes:
  vault-creds:
