#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#nx run-many --all --target=lint
npm run build:client
nx run-many --all --target=build

npm run generate:envs

git add docs/api-variables.md
git add docs/scheduler-variables.md
