export class MemoryHelper {
  public map: Partial<Record<MEM_TYPE, any>> = {};
}

export enum MEM_TYPE {
  CHANNEL_UPDATE_RESPONSE = 'CHANNEL_UPDATE_RESPONSE',
  CHANNEL_CREATE_RESPONSE = 'CHANNEL_CREATE_RESPONSE',
  INVALID_PRIVATE_KEY_RESPONSE_BODY = 'INVALID_PRIVATE_KEY_RESPONSE_BODY',
  VALID_PRIVATE_KEY_RESPONSE_BODY = 'VALID_PRIVATE_KEY_RESPONSE_BODY',
  CHANNEL_DELETE_RESPONSE = 'CHANNEL_DELETE_RESPONSE',
  SENT_MESSAGE_RESPONSE = 'SENT_MESSAGE_RESPONSE',
}
