# File: .github/workflows/workflow.yml

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Select action to excute
        options:
        - Stop
        - Start
  # schedule:
  #   - cron: '30 5 * * 1,3'
  #   - cron: '30 5 * * 2,4'

name: Auto-stop-start-aks-nodepool

jobs:

  Excute-on-dev-AKS:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.action }}
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.50.0
        inlineScript: |
          az extension add --name aks-preview
          az account show  --query user.name -o tsv 
          az aks nodepool show -g ${{ secrets.DEV_AKS_RG }} --cluster-name ${{ secrets.DEV_AKS_NAME }} --name ewf --query powerState.code -o tsv