name: Run tests
on: 
  workflow_call:
    outputs:
      affected:
        description: "Affected Apps comparing with develop branch"
        value: ${{ jobs.run_tests.outputs.affected }}
env:
  NX_BASE: origin/develop
jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.getAffected.outputs.affected_apps }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.14.2'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install NX, NPM
        run: npm install -g nx npm@8.5.0
      - name: Install dependencies
        run: npm ci
      - name: Caculate affected apps
        id: getAffected
        run: |
          affected_apps=$(nx print-affected --select=projects)
          echo $affected_apps
          echo $NX_BASE
          echo "affected_apps=$affected_apps" >>"$GITHUB_OUTPUT"
      - name: Run tests
        run: nx affected --target=test --exclude=dsb-client-gateway-api-e2e,ui-core
      - name: Run linters
        run: nx affected --target=lint --exclude=dsb-client-gateway-api-e2e,ui-core
        
