name: Run tests and getAffected
on:
  workflow_call:
    outputs:
      affected:
        description: 'Affected Apps comparing with develop branch'
        value: ${{ jobs.run_tests.outputs.affected }}
    secrets:
      NX_BASE:
        required: true
        description: 'NX comparison base'

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.getAffected.outputs.affected_apps }}
    env:
      NX_BASE: ${{ secrets.NX_BASE }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 11
      - uses: actions/setup-node@v4
        with:
          node-version: '22.21.1'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Caculate affected apps
        id: getAffected
        run: |
          affected_apps=$(npx nx print-affected --select=projects)
          echo $affected_apps
          echo $NX_BASE
          echo "affected_apps=$affected_apps" >>"$GITHUB_OUTPUT"
      - name: Run tests
        if: contains(${{ env.NX_BASE }}, 'develop')
        run: npx nx affected --target=test --exclude=dsb-client-gateway-api-e2e,ui-core
      - name: Run linters
        if: contains(${{ env.NX_BASE }}, 'develop')
        run: npx nx affected --target=lint --exclude=dsb-client-gateway-api-e2e,ui-core
