/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EthereumDIDRegistry } from "./EthereumDIDRegistry";
export * as factories from "./factories";
export { EthereumDIDRegistry__factory } from "./factories/EthereumDIDRegistry__factory";
